version: '3.5'
services:
  postgres-db:
    image: postgres:12.4
    container_name: postgres-db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=db
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  leo-iot-value-simulator:
    depends_on: [postgres-db]
    restart: on-failure
    image: ghcr.io/leo-iot/leo-iot-value-simulator
    container_name: value-simulator
    ports:
      - "80:8080"
